spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ENCRYPTED_MYSQL_HOST}:3306/poc_exam?createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${ENCRYPTED_MYSQL_USER_NAME}
    password: ${ENCRYPTED_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        ddl-auto: update
        show-sql: true
        format_sql: true

server:
  port: 8888
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        exploratory:
          include: "livenessState,readinessState,ping"
          show-details: always

FLIPT_API_TOKEN: ${ENCRYPTED_FLIPT_API_TOKEN}
FLIPT_API_URL: ${ENCRYPTED_FLIPT_API_URL}

#
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR